from typing import Any

DEBUG: bool
LOG_LEVEL: str
PUBLIC_BASE_URL: str

XLSX_BENDROS_URL: str
PDF_PLASTIKAS_URL: str
PDF_STIKLAS_URL: str

AI_PROVIDERS: list[dict[str, Any]]
AI_MODEL_ROTATION: list[dict[str, str]]

GOOGLE_CALENDAR_CREDENTIALS_FILE: str
GOOGLE_CALENDAR_SCOPES: list[str]
GOOGLE_CALENDAR_TIMEZONE: str
GOOGLE_CALENDAR_EVENT_START_HOUR: int
GOOGLE_CALENDAR_EVENT_END_HOUR: int
GOOGLE_CALENDAR_REMINDERS: list[dict[str, str | int]]

API_KEY: str
API_KEY_HEADER: str
