FROM python:3.14.1-slim

WORKDIR /app

# Install dependencies
COPY requirements-web.txt .
RUN pip install --no-cache-dir -r requirements-web.txt

COPY services/api services/api
COPY services/common services/common
COPY services/web services/web

ENV PYTHONPATH=/app

EXPOSE 3333

CMD ["python", "services/api/app.py"]
