FROM python:3.14.1-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY services/scraper services/scraper
COPY services/common services/common
COPY services/scraper/migrations services/scraper/migrations

ENV PYTHONPATH=/app

CMD ["python", "services/scraper/scheduler.py"]
