FROM python:3.14.1-slim

WORKDIR /app

# Install dependencies
COPY requirements-calendar.txt .
RUN pip install --no-cache-dir -r requirements-calendar.txt

COPY services/calendar services/calendar
COPY services/common services/common
COPY services/calendar/migrations services/calendar/migrations

ENV PYTHONPATH=/app

CMD ["python", "services/calendar/worker.py"]
